# Environment Variables
# environment variables will be populated and available to any scripts that
# are running in a container
# this is how we get information into the container

# Environment Variables
# tf_action - what action we'll take, the default action is plan
# can be altered from a new build
# tf_bucket is the s3 state bucket
# tf_table is dynamodb state table
# we are going to change the workspace name to something unique

# Artifacts
# Any artifacts generated by this process goes to the s3 bucket we created
# for artifacts
# inside that, we have a build log

#############################################################################
# VARIABLES
#############################################################################

variable "region" {
  type    = string
  default = "us-east-1"
}

variable "vpc_cidr_range" {
  type    = string
  default = "10.0.0.0/16"
}

variable "public_subnets" {
  type    = list(string)
  default = ["10.0.0.0/24", "10.0.1.0/24"]
  # default = ["10.0.0.0/24", "10.0.1.0/24", "10.0.2.0/24"]
}

#############################################################################
# PROVIDERS
#############################################################################

provider "aws" {
  version = "~> 2.0"
  region  = var.region
}

#############################################################################
# DATA SOURCES
#############################################################################

data "aws_availability_zones" "azs" {}

#############################################################################
# RESOURCES
#############################################################################

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.33.0"

  name = "${terraform.workspace}-vpc"
  cidr = var.vpc_cidr_range

  azs            = slice(data.aws_availability_zones.azs.names, 0, 1)
  public_subnets = var.public_subnets

  tags = {
    Environment = terraform.workspace
    Team        = "infra"
  }

}

#############################################################################
# OUTPUTS
#############################################################################

output "vpc_id" {
  value = module.vpc.vpc_id
}
